apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v1.2.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  template:
    metadata:
      labels:
        k8s-app: heapster
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: 10.213.42.254:10500/caozhiqiang1/heapster:v1.2.2
          name: heapster
          volumeMounts:
          - name: heapsterlog
            mountPath: /var/log/
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes.summary_api:http://10.15.137.240:11080?inClusterConfig=false
            - --sink=influxdb:http://monitoring-influxdb:8086
              #- --custom=qps:http://10.15.137.244:33611/vts_status/control?cmd=status&group=upstream@group&zone=*
            - --customsources=nginx
            - --metric_resolution=60s
            - --vmodule=*=4
            - --sink=log
            - --alsologtostderr
            - --v=4
            - --log_dir=/var/log/
        - image: 10.213.42.254:10500/caozhiqiang1/heapster:v1.2.2
          name: eventer
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /eventer
            - --source=kubernetes:http://10.15.137.240:11080?inClusterConfig=false
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --vmodule=*=4
            - --sink=log
      volumes:
        - name: heapsterlog
          hostPath:
            path: /var/log/heapster/
      nodeSelector:
        disksize: "243"

              #- --custom=qps:http://10.15.137.111:8989/qps
              #- --custom=qps:http://10.15.137.111:8990/qps
