apiVersion: v1
kind: ReplicationController
metadata:
  name: php-apache
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: php-apache
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: 10.213.42.254:10500/caozhiqiang1/hpa-example:2.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          hostPort: 8500
        volumeMounts:
        - name: definition
          mountPath: /etc/custom-metrics
        - name: definition
          mountPath: /var/cadvisor
      volumes:
      - name: definition
        configMap:
          name: cm-config
          items:
          - key: definition-json
            path: definition.json
          - key: definition-json
            path: config.json
