apiVersion: v1
kind: ReplicationController
metadata:
  name: php-apache
  namespace: kube-system
  annotations:
    metrics.alpha.kubernetes.io/custom-endpoints: '[{"api": "prometheus", "path": "/status", "port": "8080", "names": ["qps", "activeConnections"] }, { "path": "/metrics", "port": "9090", "names": ["myMetric"]}]'
spec:
  replicas: 1
  template:
    metadata:
      name: php-apache
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: docker.io/wuhaofrank/hpa-example:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
          hostPort: 8080
        volumeMounts:
        - name: definition-json
          mountPath: /etc/custom-metrics
      volumes:
      - name: definition-json
        configMap:
          name: cm-config
